### PR TITLE
Improve subs via coefficient sparsity

### PR DESCRIPTION
**Pull request by tcunis**
This PR improves the implementation of `subs` and related operations to resolve issues #28 and #29:

1. Class `PS` now distinguishes between full and sparse zeros; for a zero polynomial, only the lowest-degree zero coefficients is stored as full zero.
2. Function `prod` resorts to a recursion if the number of permutations exceeds a certain limit (currently 1M).

On a related note, function `str` now iterates over nonzero coefficients only.

### CODE REVIEW

**Review by JOlucak — CHANGES_REQUESTED** [review]
Several problems occur: 
1.) substitute zeros
Apparently if we substitute zero values e.g.g sub(p,x,0) the following polynomial is obtained
0.000261097 + 0*x_1^2 + 0*x_1*x_2 + 0*x_2^2 + 0*x_1*x_3 + 0*x_2*x_3

This causes problems e.g if we linearize a system and only need the numerical values.

2.) Original problem (out of memory)
Computation time is still high for the following example
f = Dx*subs(x_dot,[x;u],[Dx^-1*x;Du^-1*u]);
x \in \mathbb R^6 and u \in \mathbb R^3 

Furthermore, an error occurs 
Unbenannt

**Comment by tcunis** [comment]
> 1.) substitute zeros
> Apparently if we substitute zero values e.g.g `sub(p,x,0)` the following polynomial is obtained
> ```0.000261097 + 0x_1^2 + 0x_1x_2 + 0x_2^2 + 0x_1x_3 + 0x_2x_3```

I cannot reproduce this issue, I've tried the following:

```
x = casos.PS('x',3,1);
p = casos.PS(monomials(x,2),2:7) + 1;
subs(p,x,0)
```
returns 1 as expected. What is `p` in your case?

**Comment by tcunis** [comment]
Function `prod` was further improved to deal with large polynomial matrices (both size and number of coefficients) but also to handle some special classes efficiently.

**Review by JOlucak — DISMISSED** [review]

**Review by JOlucak — CHANGES_REQUESTED** [review]
After some computation time Matlab is out of order (2023b and 2021b).

Don't know why. added "test_subs.m" into demo folder to reproduce error and for future debugging.

**Comment by tcunis** [comment]
The error has been caused by multiplication with a diagonal matrix returning a polynomial with 'unnecessary' full zeros in the coefficient matrix. This has been fixed with the last commit, but substituting polynomials (other than vectors of monomials) into larger polynomials still is computationally heavy.

**Review by JOlucak — APPROVED** [review]
The new changes are very fast on the provided example.

**Pull request merged**
