### PR TITLE
New polynomial operations

### PR DESCRIPTION
**Pull request by tcunis**
This PR adds the operations `int` and `cleanpoly` to class `casos.PS` as well as extending the `jacobian` method.

### CODE REVIEW

**Comment by tcunis** [comment]
@JOlucak : Please check in particular the `cleanpoly` method.

**Review by JOlucak — CHANGES_REQUESTED** [review]
- int seems to work
- cleanpoly throws an error e.g. cleanpoly(Vsol,1e-6) where Vsol is a solution from a VS iteration. The error occurs in line 9 (The same syntax worked before)
- jacobian(f,x) should distinguish between gram and gram-like variables. Otherwise an error is thrown.

**Comment by tcunis** [comment]
>     * cleanpoly throws an error e.g. cleanpoly(Vsol,1e-6) where Vsol is a solution from a VS iteration. The error occurs in line 9 (The same syntax worked before)
> 
>     * jacobian(f,x) should distinguish between gram and gram-like variables. Otherwise an error is thrown.

Both `cleanpoly` and `jacobian` have been updated. Also, `pnorm2` from #50 has been added.

**Review by JOlucak — COMMENTED** [review]
Works!
I generated a simple test script that evaluates different cases.

**Comment by JOlucak** [comment]
Can be merged from my side.

**Review by JOlucak — APPROVED** [review]

**Pull request merged**
